-- Add order lifecycle timestamps (paid_at, delivered_at).
--
-- Backfilled historical values are approximations derived from updated_at: exact
-- transition times were never recorded. All timestamps created after deployment are
-- generated by the database at transition time (never client-supplied).
--
-- This migration is applied manually via the Supabase SQL Editor in a maintenance
-- window — never by CI.

begin;

lock table public.orders in access exclusive mode;

create temporary table order_lifecycle_migration_baseline on commit drop as
select
  count(*)::bigint as order_count,
  coalesce(sum(subtotal_centavos), 0)::numeric as subtotal_centavos,
  coalesce(sum(delivery_fee_centavos), 0)::numeric as delivery_fee_centavos,
  coalesce(sum(total_centavos), 0)::numeric as total_centavos,
  (select count(*)::bigint from public.order_items) as order_item_count
from public.orders;

create temporary table order_lifecycle_migration_timestamps on commit drop as
select id, updated_at
from public.orders;

alter table public.orders add column paid_at timestamptz;
alter table public.orders add column delivered_at timestamptz;

alter table public.orders disable trigger orders_set_updated_at;

update public.orders
set
  paid_at = case
    when status = 'new' then null
    when status = 'paid' then updated_at
    when status = 'delivered' then updated_at
    when status = 'cancelled' and payment_received = true then updated_at
    when status = 'cancelled' and payment_received = false then null
  end,
  delivered_at = case
    when status = 'new' then null
    when status = 'paid' then null
    when status = 'delivered' then updated_at
    when status = 'cancelled' and payment_received = true then null
    when status = 'cancelled' and payment_received = false then null
  end;

alter table public.orders enable trigger orders_set_updated_at;

create function public.set_order_lifecycle_timestamps()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    if new.status = 'new' then
      new.paid_at := null;
      new.delivered_at := null;
    elsif new.status = 'paid' then
      new.paid_at := coalesce(new.paid_at, now());
      new.delivered_at := null;
    elsif new.status = 'delivered' then
      new.paid_at := coalesce(new.paid_at, now());
      new.delivered_at := coalesce(new.delivered_at, now());
    elsif new.status = 'cancelled' then
      new.delivered_at := null;
    end if;
  elsif tg_op = 'UPDATE' then
    if old.status is distinct from 'paid' and new.status = 'paid' then
      new.paid_at := coalesce(old.paid_at, now());
      new.delivered_at := null;
    elsif old.status is distinct from 'delivered' and new.status = 'delivered' then
      new.paid_at := coalesce(old.paid_at, now());
      new.delivered_at := coalesce(old.delivered_at, now());
    elsif old.status is distinct from 'cancelled' and new.status = 'cancelled' then
      new.paid_at := old.paid_at;
      new.delivered_at := null;
    else
      new.paid_at := old.paid_at;
      new.delivered_at := old.delivered_at;
    end if;
  end if;
  return new;
end;
$$;

create trigger orders_set_lifecycle_timestamps
  before insert or update on public.orders
  for each row
  execute function public.set_order_lifecycle_timestamps();

alter table public.orders
  add constraint orders_lifecycle_timestamps_consistent check (
    (status = 'new' and paid_at is null and delivered_at is null)
    or (status = 'paid' and paid_at is not null and delivered_at is null)
    or (status = 'delivered' and paid_at is not null and delivered_at is not null and paid_at <= delivered_at)
    or (status = 'cancelled' and delivered_at is null)
  );

do $$
declare
  baseline order_lifecycle_migration_baseline%rowtype;
begin
  select * into strict baseline from order_lifecycle_migration_baseline;

  if (select count(*) from public.orders) <> baseline.order_count then
    raise exception 'Order count changed during lifecycle timestamps migration';
  end if;
  if (select coalesce(sum(subtotal_centavos), 0) from public.orders) <> baseline.subtotal_centavos then
    raise exception 'Order subtotal changed during lifecycle timestamps migration';
  end if;
  if (select coalesce(sum(delivery_fee_centavos), 0) from public.orders) <> baseline.delivery_fee_centavos then
    raise exception 'Delivery fee total changed during lifecycle timestamps migration';
  end if;
  if (select coalesce(sum(total_centavos), 0) from public.orders) <> baseline.total_centavos then
    raise exception 'Order total changed during lifecycle timestamps migration';
  end if;
  if (select count(*) from public.order_items) <> baseline.order_item_count then
    raise exception 'Order item count changed during lifecycle timestamps migration';
  end if;
  if exists (
    select 1
    from public.orders orders
    join order_lifecycle_migration_timestamps timestamps using (id)
    where orders.updated_at is distinct from timestamps.updated_at
  ) then
    raise exception 'Order timestamp changed during lifecycle timestamps migration';
  end if;
  if exists (
    select 1
    from public.orders
    where not (
      (status = 'new' and not payment_received)
      or (status in ('paid', 'delivered') and payment_received)
      or status = 'cancelled'
    )
  ) then
    raise exception 'Payment/status consistency violated during lifecycle timestamps migration';
  end if;
  if exists (
    select 1
    from public.orders
    where not (
      (status = 'new' and paid_at is null and delivered_at is null)
      or (status = 'paid' and paid_at is not null and delivered_at is null)
      or (status = 'delivered' and paid_at is not null and delivered_at is not null and paid_at <= delivered_at)
      or (status = 'cancelled' and delivered_at is null)
    )
  ) then
    raise exception 'Lifecycle timestamps inconsistent after migration';
  end if;
end;
$$;

commit;
